# Generated by Django 4.2.1 on 2023-07-26 15:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("otp", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "used_for",
                    models.CharField(
                        choices=[
                            ("reg", "Registration"),
                            ("fp", "Forgot Password"),
                            ("rmn", "RMN"),
                            ("custom", "Custom"),
                            ("otp", "Otp"),
                            ("oth", "Others"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("otp_attempts", models.SmallIntegerField(blank=True, null=True)),
                ("otp_sent", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("body_html", tinymce.models.HTMLField()),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "used_for",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("password_change", "Password Change"),
                            ("otp", "Otp"),
                            ("oth", "Others"),
                        ],
                        default="",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is Active")),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
            },
        ),
    ]
