# Generated by Django 5.0.4 on 2024-06-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='code',
        ),
    ]
