# Generated by Django 5.0.4 on 2024-06-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_counter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='keyword',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_counter', to='master.keyword'),
        ),
    ]
