# Generated by Django 5.0.4 on 2024-05-01 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('processor', models.CharField(max_length=100)),
                ('ram_capacity', models.IntegerField(help_text='RAM capacity in GB')),
                ('storage_capacity', models.IntegerField(help_text='Storage capacity in GB')),
                ('operating_system', models.CharField(max_length=100)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('form_factor', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.CharField(help_text='E.g., Router, Switch, Modem', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('network_speed', models.CharField(blank=True, max_length=100)),
                ('port_count', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('printer_type', models.CharField(help_text='E.g., Laser, Inkjet, Dot matrix', max_length=100)),
                ('is_color', models.BooleanField(default=False)),
                ('is_network_printer', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, max_length=100)),
                ('paper_sizes_supported', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printer',
                'verbose_name_plural': 'Printers',
            },
        ),
    ]
