# Generated by Django 5.0.4 on 2024-08-14 07:51

import django.db.models.deletion
import monitor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('node_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeLogFile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=monitor.models.upload_to_original_filename)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('metric_calculation', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_zone_offset_start', models.CharField(blank=True, max_length=6, null=True)),
                ('time_zone_offset_end', models.CharField(blank=True, max_length=6, null=True)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.node')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeMetric',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(blank=True, choices=[('iub_throughput_utilization', 'IUB throughput utilization'), ('voice_traffic', 'Voice Traffic'), ('nas_success_rate_cs', 'NAS success rate cs'), ('rrc_success_rate_cs', 'RRC success rate cs'), ('rrc_success_rate_ps', 'RRC success rate ps'), ('hs_drop', 'HS drop'), ('csfb_success_rate', 'CSFB success rate')], default='', max_length=255, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('logfile', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.nodelogfile')),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.node')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
