# Generated by Django 5.0.4 on 2024-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelogfile',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
