# Generated by Django 5.0.4 on 2024-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_nodelogfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodelogfile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='nodelogfile',
            name='time_zone_offset_end',
        ),
        migrations.RemoveField(
            model_name='nodelogfile',
            name='time_zone_offset_start',
        ),
        migrations.AlterField(
            model_name='nodelogfile',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nodelogfile',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
