# Generated by Django 5.0.4 on 2024-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_nodelogfile_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodelogfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nodemetric',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='nodelogfile',
            unique_together={('node', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='nodemetric',
            unique_together={('node', 'logfile', 'metric')},
        ),
    ]
