# Generated by Django 5.0.4 on 2024-06-17 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_counter_keyword'),
        ('monitor', '0025_alter_dio_id_alter_fiber_id_alter_host_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterLog',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(blank=True, default='', null=True)),
                ('keyword_no', models.IntegerField()),
                ('counter_no', models.IntegerField()),
                ('counter_value', models.IntegerField()),
                ('counter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.counter')),
                ('created_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.keyword', to_field='code')),
                ('modified_by', models.ForeignKey(blank=True, default='', editable=False, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Router Log',
                'verbose_name_plural': 'Router Logs',
            },
        ),
    ]
