# Generated by Django 5.0.4 on 2024-06-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_routerlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiber',
            name='dio',
        ),
        migrations.RemoveField(
            model_name='portlog',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostlog',
            name='host',
        ),
        migrations.RemoveField(
            model_name='port',
            name='host',
        ),
        migrations.RemoveField(
            model_name='portlog',
            name='port',
        ),
        migrations.DeleteModel(
            name='Dio',
        ),
        migrations.DeleteModel(
            name='Fiber',
        ),
        migrations.DeleteModel(
            name='HostLog',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='PortLog',
        ),
    ]
