# Generated by Django 5.0.4 on 2024-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_remove_fiber_dio_remove_portlog_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerlog',
            name='counter_name',
            field=models.CharField(max_length=50, verbose_name='Counter Name'),
        ),
        migrations.AlterField(
            model_name='routerlog',
            name='counter_no',
            field=models.CharField(max_length=50, verbose_name='Counter No'),
        ),
        migrations.AlterField(
            model_name='routerlog',
            name='keyword',
            field=models.CharField(max_length=30, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='routerlog',
            name='keyword_no',
            field=models.CharField(max_length=50, verbose_name='Keyword No'),
        ),
    ]
