# Generated by Django 5.0.4 on 2024-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0032_alter_routerlogscore_sdcch_drop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerlogscore',
            name='sdcch_drop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='routerlogscore',
            name='tchdrop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='routerlogscore',
            name='traffic_voice_2g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
