# Generated by Django 5.0.4 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0033_alter_routerlogscore_sdcch_drop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerlogscore',
            name='sdcch_drop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerlogscore',
            name='tchdrop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerlogscore',
            name='traffic_voice_2g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
